import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Nike Shoe 1",
    price: 3999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nike-shoe1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Nike Shoe 2",
    price: 2999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nike-shoe2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  }, 
  {
    _id: uuid(),
    productName: "Nike Shoe 3",
    price: 4999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nike-shoe3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  }, 
  {
    _id: uuid(),
    productName: "Nike Shoe 4",
    price: 5999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nike-shoe4.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Nike Shoe 5",
    price: 4599,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nike-shoe5.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance Shoe 1",
    price: 5999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nb-shoe-1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance Shoe 2",
    price: 6999,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nb-shoe-2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance Shoe 3",
    price: 4599,
    categoryName: "footwear",
    imgSrc:"../assets/prod-nb-shoe-3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Adidas Shoe 1",
    price: 3599,
    categoryName: "footwear",
    imgSrc:"../assets/prod-adidas1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Adidas Shoe 2",
    price: 3599,
    categoryName: "footwear",
    imgSrc:"../assets/prod-adidas2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Adidas Shoe 3",
    price: 4599,
    categoryName: "footwear",
    imgSrc:"../assets/prod-adidas3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "H&M Shirt 1",
    price: 999,
    categoryName: "men",
    imgSrc:"../assets/prod-hm1.webp",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "H&M Shirt 2",
    price: 1199,
    categoryName: "men",
    imgSrc:"../assets/prod-hm2.webp",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "H&M Shirt 3",
    price: 1499,
    categoryName: "men",
    imgSrc:"../assets/prod-hm3.webp",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "H&M Shirt 4",
    price: 1999,
    categoryName: "men",
    imgSrc:"../assets/prod-hm4.webp",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance T-Shirt 1",
    price: 4999,
    categoryName: "men",
    imgSrc:"../assets/prod-nb-shirt1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance T-Shirt 2",
    price: 2999,
    categoryName: "men",
    imgSrc:"../assets/prod-nb-shirt2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance T-Shirt 3",
    price: 2599,
    categoryName: "men",
    imgSrc:"../assets/prod-nb-shirt3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "New Balance T-Shirt 4",
    price: 5999,
    categoryName: "men",
    imgSrc:"../assets/prod-nb-shirt4.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "W",
    price: 1999,
    categoryName: "women",
    imgSrc:"../assets/prod-w-dress1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 3
  },
  {
    _id: uuid(),
    productName: "W",
    price: 1599,
    categoryName: "women",
    imgSrc:"../assets/prod-w-dress2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 1.5
  },
  {
    _id: uuid(),
    productName: "W",
    price: 1899,
    categoryName: "women",
    imgSrc:"../assets/prod-w-dress3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 2
  },
  {
    _id: uuid(),
    productName: "W",
    price: 1999,
    categoryName: "women",
    imgSrc:"../assets/prod-w-dress4.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 3.8
  },
  {
    _id: uuid(),
    productName: "Libas",
    price: 1899,
    categoryName: "women",
    imgSrc:"../assets/prod-libas-dress1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 3.5
  },
  {
    _id: uuid(),
    productName: "Libas",
    price: 1899,
    categoryName: "women",
    imgSrc:"../assets/prod-libas-dress2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4.1
  },
  {
    _id: uuid(),
    productName: "Libas",
    price: 1999,
    categoryName: "women",
    imgSrc:"../assets/prod-libas-dress3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4.2
  },
  {
    _id: uuid(),
    productName: "Libas",
    price: 2299,
    categoryName: "women",
    imgSrc:"../assets/prod-libas-dress4.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4.5
  },
  {
    _id: uuid(),
    productName: "Levi's",
    price: 1499,
    categoryName: "women",
    imgSrc:"../assets/prod-levis-dress1.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 5
  },
  {
    _id: uuid(),
    productName: "Levi's",
    price: 1999,
    categoryName: "women",
    imgSrc:"../assets/prod-levis-dress2.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 4
  },
  {
    _id: uuid(),
    productName: "Levi's",
    price: 1399,
    categoryName: "women",
    imgSrc:"../assets/prod-levis-dress3.jpg",
    inStock: true,
    originalPrice: "9999",
    percentOff: "60%",
    fastDelivery: false,
    ratings: 3
  },
];
